"""AF2 field descriptor registry generated from ``configurations_schema``.

The registry gives every editable engineering value a stable semantic field ID
(Â§6.2) plus type, unit, constraints, default, applicability, invalidation, and
UI-location metadata. Base descriptors are generated by walking the SimpleDB
schema; hand-authored metadata (units/docs/dependencies/applicability/impact/
UI) is layered on from :mod:`foammesh.core.facade.field_metadata`, because that
information cannot be inferred from the legacy type system.

The generated semantic IDs are a frozen part of the AF1V contract for the ten
AF1V fields; AF2 adds the rest against the same dotted ``area.group.field``
shape.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum

from foammesh.support.simple_db.simple_schema import (
    BoolType, EnumType, FloatType, IntType, PrimitiveType, SchemaList)

from foammesh.db.configurations_schema import schema as CONFIGURATIONS_SCHEMA

from .field_metadata import DEFAULT_INVALIDATION, FIELD_OVERRIDES, GROUP_METADATA


class FieldType(str, Enum):
    NUMBER = 'number'
    INTEGER = 'integer'
    BOOLEAN = 'boolean'
    TEXT = 'text'
    ENUM = 'enum'


# Storage-path prefixes (longest match wins) -> semantic area namespace.
AREA_BY_PREFIX = {
    'mesh': 'mesh',
    'gmsh/healing': 'gmsh.describe_geometry',
    'gmsh/globalSizing': 'gmsh.global_sizing',
    'gmsh/algorithms': 'gmsh.global_sizing',
    'gmsh/parallel': 'gmsh.global_sizing',
    # Plan 30 WP12. The farfield is part of describing the domain, so it sits
    # with the import and the healing rather than with the sizing.
    'gmsh/farfield': 'gmsh.describe_geometry',
    'gmsh/sizeFields': 'gmsh.size_fields',
    # Plan 29 WP8. A per-surface size is a size field with the geometry
    # already chosen, so it belongs on the same page and in the same area.
    'gmsh/surfaceSizes': 'gmsh.size_fields',
    'gmsh/output': 'gmsh.compute',
    'gmsh/curveControls': 'gmsh.curve_controls',
    'gmsh/volumeControls': 'gmsh.volume_controls',
    # Plan 31 FC-C. Automatic structuring is a per-volume result, so it is
    # asked for and reported on the page that already speaks about volumes.
    'gmsh/structuring': 'gmsh.volume_controls',
    'gmsh/boundaryLayers': 'gmsh.boundary_layers',
    'gmsh/periodicPairs': 'gmsh.periodic',
    'gmsh/optimization': 'gmsh.compute',
    # Plan 31. How the staged surfaces are declared and searched. It is a
    # meshing input, not a geometry-import one -- nothing here changes the
    # geometry, only what snappyHexMesh is told about it.
    'snappyGeometry': 'meshing.geometry',
    'baseGrid': 'meshing.base_grid',
    'castellation': 'meshing.castellation',
    'snap/bufferLayer': 'meshing.snap.buffer_layer',
    'snap': 'meshing.snap',
    'addLayers': 'meshing.layers',
    'meshQuality/relaxed': 'quality.thresholds.relaxed',
    'meshQuality': 'quality.thresholds',
    # Plan 31. checkMesh's own command line. Deliberately *not* under
    # `quality.thresholds`: those are the limits handed to the mesher, these
    # are the limits the finished mesh is judged against, and the QA page has
    # been muddling the two since it was written.
    'meshCheck': 'quality.check',
    # Plan 31. The extraction stage has its own workflow task and its own
    # page, so its settings get their own area rather than being filed under
    # castellation, which is where the included angle still lives (per
    # refinement group, because it is per surface).
    'surfaceFeatures': 'meshing.surface_features',
    # Plan 29 WP7. snappyHexMesh's own diagnostic output -- it belongs with the
    # meshing controls, not in an area of its own.
    'snappyAdvanced': 'meshing.snappy_advanced',
}

# Storage leaf -> curated semantic leaf. The first ten are frozen by AF1V; the
# rest disambiguate acronyms or match the reviewed field vocabulary.
LEAF_ALIASES = {
    'numCellsX': 'cells.x', 'numCellsY': 'cells.y', 'numCellsZ': 'cells.z',
    'boundingHex6': 'bounding_hex6',
    'maxGlobalCells': 'max_global_cells', 'maxLocalCells': 'max_local_cells',
    'nCellsBetweenLevels': 'cells_between_levels',
    'nSmoothPatch': 'smooth_patch_iterations',
    'nGrow': 'growth_cells',
    'GETMeTransformationParameter': 'getme_transformation_parameter',
    'maxNonOrtho': 'max_non_orthogonality',
    'vtkNonManifoldEdges': 'vtk_non_manifold_edges',
    'vtkBoundaryEdges': 'vtk_boundary_edges',
}

# Top-level storage keys that are internal bookkeeping, not editable fields.
INTERNAL_KEYS = {'version'}

# Storage keys whose subtree is a workflow selector rather than a mesh field.
STANDALONE_SEMANTIC = {'step': 'workflow.step'}

_CAMEL = re.compile(r'(?<!^)(?=[A-Z])')


def _snake(text: str) -> str:
    return _CAMEL.sub('_', text).lower()


def _area_for(path: str) -> str:
    parent = path.rsplit('/', 1)[0] if '/' in path else ''
    for prefix in sorted(AREA_BY_PREFIX, key=len, reverse=True):
        if parent == prefix or parent.startswith(prefix + '/'):
            suffix = parent[len(prefix):].strip('/')
            base = AREA_BY_PREFIX[prefix]
            return f'{base}.{_snake(suffix.replace("/", "."))}' if suffix else base
    return _snake(parent.replace('/', '.')) if parent else ''


def _semantic_id(path: str) -> str:
    if path in STANDALONE_SEMANTIC:
        return STANDALONE_SEMANTIC[path]
    leaf = path.rsplit('/', 1)[-1]
    semantic_leaf = LEAF_ALIASES.get(leaf, _snake(leaf))
    area = _area_for(path)
    return f'{area}.{semantic_leaf}' if area else semantic_leaf


def _number(value):
    if value is None or value == '':
        return None
    try:
        number = float(value)
    except (TypeError, ValueError):
        return value
    return int(number) if number.is_integer() else number


@dataclass(frozen=True)
class FieldDescriptor:
    id: str
    storage_path: str
    title: str
    value_type: FieldType
    unit: str | None = None
    default: object = None
    minimum: float | None = None
    maximum: float | None = None
    exclusive_minimum: bool = False
    exclusive_maximum: bool = False
    enum: tuple[str, ...] | None = None
    read_only: bool = False
    required: bool = True
    applies_when: tuple[str, ...] = ()
    invalidates: tuple[str, ...] = ()
    ui_location: str = ''
    documentation: str = ''

    def to_dict(self) -> dict:
        return {
            'id': self.id, 'title': self.title, 'value_type': self.value_type.value,
            'unit': self.unit, 'default': self.default,
            'minimum': self.minimum, 'maximum': self.maximum,
            'exclusive_minimum': self.exclusive_minimum,
            'exclusive_maximum': self.exclusive_maximum,
            'enum': list(self.enum) if self.enum is not None else None,
            'read_only': self.read_only, 'required': self.required,
            'applies_when': list(self.applies_when),
            'invalidates': list(self.invalidates),
            'ui_location': self.ui_location, 'documentation': self.documentation,
        }

    def json_schema(self) -> dict:
        node: dict = {'title': self.title}
        if self.value_type is FieldType.INTEGER:
            node['type'] = 'integer'
        elif self.value_type is FieldType.NUMBER:
            node['type'] = 'number'
        elif self.value_type is FieldType.BOOLEAN:
            node['type'] = 'boolean'
        elif self.value_type is FieldType.ENUM:
            node['type'] = 'string'
            node['enum'] = list(self.enum or ())
        else:
            node['type'] = 'string'
        if self.unit:
            node['x-unit'] = self.unit
        if self.default is not None:
            node['default'] = self.default
        if self.minimum is not None:
            node['exclusiveMinimum' if self.exclusive_minimum else 'minimum'] = self.minimum
        if self.maximum is not None:
            node['exclusiveMaximum' if self.exclusive_maximum else 'maximum'] = self.maximum
        if self.documentation:
            node['description'] = self.documentation
        return node


def _descriptor_type(primitive: PrimitiveType) -> FieldType:
    if isinstance(primitive, EnumType):
        return FieldType.ENUM
    if isinstance(primitive, BoolType):
        return FieldType.BOOLEAN
    if isinstance(primitive, IntType):
        return FieldType.INTEGER
    if isinstance(primitive, FloatType):
        return FieldType.NUMBER
    return FieldType.TEXT


def _build_descriptor(path: str, primitive: PrimitiveType) -> FieldDescriptor:
    field_id = _semantic_id(path)
    value_type = _descriptor_type(primitive)
    minimum = maximum = None
    exclusive_min = exclusive_max = False
    enum_options = None
    default = primitive.default()
    if value_type is FieldType.ENUM:
        enum_options = tuple(item.value if isinstance(item.value, str) else item.name
                             for item in primitive._cls)
        default = default if isinstance(default, str) else getattr(default, 'name', default)
    elif value_type in (FieldType.INTEGER, FieldType.NUMBER):
        minimum = _number(primitive._lowLimit) if primitive._lowLimit is not None else None
        maximum = _number(primitive._highLimit) if primitive._highLimit is not None else None
        exclusive_min = minimum is not None and not primitive._lowLimitInclusive
        exclusive_max = maximum is not None and not primitive._highLimitInclusive
        default = _number(default)
    elif value_type is FieldType.BOOLEAN:
        default = bool(default)

    group_meta = _group_metadata(path)
    override = FIELD_OVERRIDES.get(field_id, {})
    invalidates = tuple(override.get('invalidates', group_meta.get(
        'invalidates', DEFAULT_INVALIDATION)))
    ui_location = override.get('ui_location', group_meta.get('ui_location', ''))
    documentation = override.get('documentation', '')
    unit = override.get('unit', group_meta.get('units', {}).get(field_id.rsplit('.', 1)[-1]))
    applies_when = tuple(override.get(
        'applies_when', group_meta.get('applies_when', _applicability(path))))
    read_only = override.get('read_only', path in STANDALONE_SEMANTIC)

    return FieldDescriptor(
        id=field_id, storage_path=path,
        title=override.get('title', _title(field_id)),
        value_type=value_type, unit=unit, default=override.get('default', default),
        minimum=minimum, maximum=maximum,
        exclusive_minimum=exclusive_min, exclusive_maximum=exclusive_max,
        enum=enum_options, read_only=read_only,
        required=primitive.isRequired(), applies_when=applies_when,
        invalidates=invalidates, ui_location=ui_location, documentation=documentation)


def _group_metadata(path: str) -> dict:
    parent = path.rsplit('/', 1)[0] if '/' in path else path
    for prefix in sorted(GROUP_METADATA, key=len, reverse=True):
        if parent == prefix or parent.startswith(prefix + '/') or path == prefix:
            return GROUP_METADATA[prefix]
    return {}


def _applicability(path: str) -> tuple[str, ...]:
    """A field applies only when its parent group's ``disabled`` flag is off."""
    parent = path.rsplit('/', 1)[0] if '/' in path else ''
    leaf = path.rsplit('/', 1)[-1]
    if leaf == 'disabled' or not parent:
        return ()
    disabled_path = f'{parent}/disabled'
    if _schema_has(disabled_path):
        return (f'{_semantic_id(parent + "/disabled")} == false',)
    return ()


def _schema_has(path: str) -> bool:
    node = CONFIGURATIONS_SCHEMA
    for part in path.split('/'):
        if isinstance(node, dict) and part in node:
            node = node[part]
        else:
            return False
    return isinstance(node, PrimitiveType)


def _title(field_id: str) -> str:
    return field_id.rsplit('.', 1)[-1].replace('_', ' ').replace('.', ' ').strip().title()


@dataclass
class CollectionSchema:
    """A repeated entity collection (``IntKeyList``) and its element schema."""
    collection_id: str
    storage_path: str
    element_schema: dict
    element_fields: dict = field(default_factory=dict)


class FieldRegistry:
    def __init__(self):
        self._by_id: dict[str, FieldDescriptor] = {}
        self._by_path: dict[str, FieldDescriptor] = {}
        self.collections: dict[str, CollectionSchema] = {}
        # C31-08. Repeated rows that live *inside* one element of a collection
        # -- the ``(distance level)`` bands of a single volume refinement.
        # They are not entities of their own: a band has no meaning apart from
        # the region that owns it, and creating one through
        # ``<collection>.create`` would have nowhere to put it. They are kept
        # apart from ``collections`` for exactly that reason -- the operation
        # registry is built from ``collections``, and publishing
        # create/patch/remove for a row that cannot be addressed on its own
        # would be a promise the facade cannot keep. They still carry full
        # descriptors, so the AF0/AF8 coverage gate sees them.
        self.nested_collections: dict[str, CollectionSchema] = {}

    def add(self, descriptor: FieldDescriptor) -> None:
        if descriptor.id in self._by_id:
            raise ValueError(f'duplicate semantic field id: {descriptor.id}')
        self._by_id[descriptor.id] = descriptor
        self._by_path[descriptor.storage_path] = descriptor

    def __contains__(self, field_id: str) -> bool:
        return field_id in self._by_id

    def __len__(self) -> int:
        return len(self._by_id)

    def get(self, field_id: str) -> FieldDescriptor:
        try:
            return self._by_id[field_id]
        except KeyError as error:
            from .errors import ValidationFailedError
            raise ValidationFailedError('unknown facade field', details={
                'field_id': field_id}) from error

    def ids(self) -> tuple[str, ...]:
        return tuple(sorted(self._by_id))

    def descriptors(self) -> tuple[FieldDescriptor, ...]:
        return tuple(self._by_id[key] for key in sorted(self._by_id))

    def by_storage_path(self, storage_path: str):
        """The descriptor a schema path produces, or ``None``.

        Semantic field ids are snake_case and areas are remapped, so a caller
        holding a storage path cannot construct the id by string surgery.
        """
        return self._by_path.get(storage_path)

    def storage_map(self) -> dict[str, str]:
        return {field_id: descriptor.storage_path
                for field_id, descriptor in self._by_id.items()}

    def json_schema(self) -> dict:
        return {
            'type': 'object',
            'properties': {descriptor.id: descriptor.json_schema()
                           for descriptor in self.descriptors()},
        }


def _walk(node: dict, prefix: str, registry: FieldRegistry) -> None:
    for key, value in node.items():
        path = f'{prefix}/{key}' if prefix else key
        if not prefix and key in INTERNAL_KEYS:
            continue
        if isinstance(value, SchemaList):
            collection_id = _collection_id(path)
            element_schema = value.elementSchema()
            registry.collections[collection_id] = CollectionSchema(
                collection_id, path, element_schema)
            _walk_nested(element_schema, f'{path}/{{id}}', registry)
        elif isinstance(value, dict):
            _walk(value, path, registry)
        elif isinstance(value, PrimitiveType):
            registry.add(_build_descriptor(path, value))


def _walk_nested(node: dict, prefix: str, registry: FieldRegistry) -> None:
    """Register repeated rows found inside a collection element.

    C31-08 added ``castellation/refinementVolumes/{id}/bands``, the first of
    these. Without this pass its two leaves are schema paths the AF0 inventory
    finds in source and the AF2 registry has never heard of, which is the
    silent gap ``missing_from_registry`` exists to catch.
    """
    for key, value in node.items():
        path = f'{prefix}/{key}'
        if isinstance(value, SchemaList):
            collection_id = _collection_id(path)
            registry.nested_collections[collection_id] = CollectionSchema(
                collection_id, path, value.elementSchema())
        elif isinstance(value, dict):
            _walk_nested(value, path, registry)


def _collection_id(path: str) -> str:
    mapping = {
        'geometry': 'geometry.items',
        'region': 'regions.items',
        'castellation/refinementSurfaces': 'meshing.castellation.surface_refinements',
        'castellation/refinementVolumes': 'meshing.castellation.volume_refinements',
        'castellation/refinementVolumes/{id}/bands':
            'meshing.castellation.volume_refinement_bands',
        'castellation/featureBands': 'meshing.castellation.feature_bands',
        'addLayers/layers': 'meshing.layers.groups',
        'interfacePairs': 'geometry.interface_pairs',
        'gmsh/sizeFields': 'gmsh.size_fields.controls',
        'gmsh/surfaceSizes': 'gmsh.surface_sizes.controls',
        'gmsh/curveControls': 'gmsh.curve_controls.controls',
        'gmsh/volumeControls': 'gmsh.volume_controls.controls',
        'gmsh/periodicPairs': 'gmsh.periodic_pairs.controls',
    }
    return mapping.get(path, _snake(path.replace('/', '.')))


def build_field_registry() -> FieldRegistry:
    registry = FieldRegistry()
    _walk(CONFIGURATIONS_SCHEMA, '', registry)
    return registry


REGISTRY = build_field_registry()
